version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: mdillon/postgis
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      PGDATA: /data/postgres
    volumes:
      - unc-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  unc-data:
