version: "3.5"
services:
  proxy:
    image: nginx:latest
    container_name: proxy-nginx
    links:
      - backend
      - martin
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - unc
    restart: unless-stopped
  martin:
    image: urbica/martin
    container_name: martin
    hostname: martin
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      WATCH_MODE: "true"
      DANGER_ACCEPT_INVALID_CERTS: "true"
      DATABASE_URL: "postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}"
    networks:
      - unc
  backend:
    build:
      context: ./
    container_name: backend
    hostname: backend
    ports:
      - 8000:8000
    networks:
      - unc
    env_file: .env
    restart: unless-stopped
volumes:
  unc-data-v1:
  node_modules:
  frontend:
networks:
  unc:
    driver: bridge
