name: ci

on:
  push:
    branches:
      - main
      - stage
      - test
      - dev
  pull_request:
    branches:
      - main
      - stage
      - test
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node env 📦
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node }}
          scope: '@geospoc'
          cache: 'npm'

      - name: Upgrade npm ✨
        run: npm i -g npm@latest

      - name: Install dependencies 🚀
        run: npm ci --prefer-offline --no-audit --no-optional

      - name: Run linter(s) 👀
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          continue_on_error: false
          git_name: github-actions[bot]
          git_email: github-actions[bot]@users.noreply.github.com
          auto_fix: false
          eslint: true
          eslint_extensions: js,ts,vue
          prettier: true
          prettier_extensions: js,ts,vue
          neutral_check_on_warning: true
